### ISSUE TITLE
Add probe data is set made available via MQTT

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/appmetrics#110]
when monitoring the appmetrics data with the Health Center client, none of the probe information is being transmitted.  Need to have the appmetrics agent enhanced to transmit probe data

**Comment by hhellyeribm** [comment]
Changed the label - reading the above description this sounds like a bug.

**Comment by seabaylea** [comment]
This isn't a bug - it's a deliberate design decision. The only current consumer of the MQTT connection - the Health Centre plug-in for the Eclipse IDE - does not utilise the data, therefore there was little point in paying the performance cost of transmitting the data.

Adding the JS level data into the set transmitted via MQTT makes sense, if/when a consumer (i.e., Health Centre) wants access to it. It sounds like this is a request for that to happen.

At the same time, I think we should be looking at removing the creation of the MQTT connection by default where 'appmetrics' is required into the application rather than launched using the `node-hc` CLI . That would happen under a different issue/enhancement.
