### ISSUE TITLE
Support an HTTP based API for non-Eclipse clients

### ISSUE THREAD

**Issue by cfjedimaster** [RuntimeTools/appmetrics#179]
I'd like to build my own tooling to render appmetric data as opposed to using the Eclipse plugin. It would be cool if the healthcenter integration could be configured to support a REST-based API so I could simply ping it to get data in a JSON format. This would allow other editors to connect to the data.

**Comment by tunniclm** [comment]
There are a number of things to mention here:

* You can get the data using the `monitor()` API in-process and expose it via HTTP. There is an example of doing so via HTML in the [appmetrics-dash](https://github.com/RuntimeTools/appmetrics-dash) project.
* We want to extend the `monitor()` API at some point to allow connection to other (remote) appmetrics instances. This would allow Node.js clients the load appmetrics and connect to MQTT and negotiate the wire protocol / formats.
* We want to move the wire protocol / format for HealthCenter towards streaming JSON rather than the mixture of legacy formats that are currently used. This would allow other clients to connect to the MQTT broker and more easily interact with appmetrics.

The latter two points are not planned in a milestone as far as I know, but I think they are a desirable direction to head towards.

**Comment by cfjedimaster** [comment]
Sounds good - thank you for the tips!

**Comment by sjanuary** [comment]
Having re-implemented appmetrics-dash on top of appmetrics I think the current API is probably 'good enough' to be able to close this for now and appmetrics-dash provides a good example to people who want to write their own tooling.  Please re-open or open a new issue if you think there's anything specifically missing for your use case, or we're open to pull requests.
