### ISSUE TITLE
Child request events need to have top level url in the event data

### ISSUE THREAD

**Issue by email2ravig** [RuntimeTools/appmetrics#374]
When a child request is triggered as part of a top level request, the child request event needs to have information of the top level request. For example, if a http request makes a mongo call, the MongoDB event needs to have url of the http request in the event data. This enhancement needs to be done for all the child request events (http outbound, LevelDB, MySQL, MongoDB, PostgreSQL, MQTT, riak etc). This is important as it helps relate a performance bottleneck to the impacted requests. It also helps in deriving analytic patterns.

**Comment by tobespc** [comment]
@ravigadekarla Are you using request tracking ?  How are you getting hold of the child request data ?  This should be possible already as you would walk the tree from the parent if using request tracking

**Comment by ravigadekarla** [comment]
@tobespc Yes with request tracking, we are able to get the data but the problem is that overhead is relatively higher as it gives data related to all the child requests that occurred as part of that top level request. For example, I as a user want to know if a mongo call takes more than 100 ms and when that happens, I want to know the top level request (business request) that triggered the call. I am not interested in other child requests the top level request makes. Currently, in order to get the data, I need to enable request tracking which is expensive as compared to enabling just http and mongo events.

**Comment by sjanuary** [comment]
I don't think this is possible without actually re-implementing most of the way request mode works, which will add the same overhead. It might be possible to streamline or improve request mode itself (e.g. filter out certain types of data) but I don't think this is going to work for metrics mode.
