### ISSUE TITLE
Moment is not installed for aspect.js

### ISSUE THREAD

**Issue by anthonywebb** [RuntimeTools/appmetrics#453]
/appmetrics/lib/aspect.js:100:24 needs "moment" installed, but does not have it.  Should it be added to the package.json to it gets picked up?

**Comment by stalleyj** [comment]
What problem are you seeing ?  Where do you think aspect.js uses "moment" ?

**Comment by gibfahn** [comment]
Looks like Github messed up your formatting, but I think it was originally `/appmetrics/lib/aspect.js:100:24`?

[lib/aspect.js#L100](https://github.com/RuntimeTools/appmetrics/blob/master/lib/aspect.js#L100) is:

```js
var ret = existing.apply(this, arguments);
```

**Comment by seabaylea** [comment]
My guess would be that the underlying error is being generated from a function that's being monkey-patched by aspects.js rather than aspects.js itself.

**Comment by sam-github** [comment]
Stable github source link: https://github.com/RuntimeTools/appmetrics/blob/a4c68280307f9e2fdad165e82b3a5e9d05280262/lib/aspect.js#L100

**Comment by sam-github** [comment]
@anthonywebb  Since aspect replaces node's require, and then calls it again, any failure to require a dependency will have appmetrics in the stack trace, but its not appmetrics that is doing the original require, you need to search a bit further up the stack trace to find the source of the unresolvable dependency.

If you include the full stack trace, we should be able to tell you what module isn't correctly specifying its dependencies, though I suspect that if you look a bit higher up the trace, you'll find it yourself.

**Comment by anthonywebb** [comment]
@sam-github thanks for the clarification. I did indeed find where moment was failing, and although it looked on the surface that it was coming from appmetrics, it indeed was not...  Sorry for the false alarm!
