### ISSUE TITLE
CITGM - Appmetrics is failing

### ISSUE THREAD

**Issue by gdams** [RuntimeTools/appmetrics#481]
```bash
> appmetrics@3.1.0 pretest /svt/jenkins/workspace/SVT-V6-Supported_Modules-CITGM/ARCH/s390x/GCC/gcc48/OS/rhel7/TAG/svt/tmp/b02db2a0-5acc-4bdb-a68f-3b76447227c3/appmetrics
 > eslint .
 Oops! Something went wrong! :(
 ESLint: 4.8.0.
 ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:
     eslint --init
 ESLint looked for configuration files in /svt/jenkins/workspace/SVT-V6-Supported_Modules-CITGM/ARCH/s390x/GCC/gcc48/OS/rhel7/TAG/svt/tmp/b02db2a0-5acc-4bdb-a68f-3b76447227c3/appmetrics and its ancestors.
 If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
 npm ERR! Test failed.  See above for more details.
```

recreate with `citgm appmetrics`

**Comment by mattcolegate** [comment]
I've taken a look at appmetrics installations on npm as far back as 2.0.1 and all will fail this test, because we're not including any hidden (dot) files in our packaging. This means .eslintrc is not making it into our published NPM offering, and causing the above. I will adjust our packaging process to pick up the hidden files.

**Comment by gdams** [comment]
Thanks, I'm curious how this ever worked!

**Comment by mattcolegate** [comment]
Don't think it ever did!
Packaging fix has been landed. This issue will be resolved in the next release of appmetrics that gets pushed to npm.org (likely to be in the next fortnight).
