### ISSUE TITLE
Build error on node 10.3.0

### ISSUE THREAD

**Issue by SeanSobey** [RuntimeTools/appmetrics#526]
After upgrading to Node 10.3.0 I seem unable to build `(npm rebuild)` appmetrics ([again](https://github.com/RuntimeTools/appmetrics/issues/512)): 

```
LINK : fatal error LNK1194: cannot delay-load 'node.exe' due to import of data symbol '"__declspec(dllimport) const std::basic_ostream<char,struct std::char_traits<char> >::`vftable'" (__imp_??_7?$basic_ostream@DU?$char_traits@D@std@@@std@@6B@)'; link without /DELAYLOAD:node.exe [<app path>\node_modules\appmetrics\build\nodeprofplugin.vcxproj]
```

I am still using msbuild 14.0

**Comment by sjanuary** [comment]
@SeanSobey we're not [officially supporting](https://github.com/RuntimeTools/appmetrics#supported-platforms) Node 10 yet and although I think it works with no changes on Linux it looks like there's some work to do on Windows.  We're happy to review and accept PRs, otherwise it will be looked at when someone has time for it which may not be very quickly unfortunately due to other commitments.
