### ISSUE TITLE
Usage with Node Cluster

### ISSUE THREAD

**Issue by gustavomassa** [RuntimeTools/appmetrics#550]
Hello,

How does appmetrics behave when using cluster module with different workers running?
Does it monitor all the process (Master and workers) and send the metrics assuming the node cluster is a single process? Or does it should send metrics for each running worker and a separated one for master?

#https://github.com/RuntimeTools/appmetrics-dash/issues/88

Thanks!

**Comment by sjanuary** [comment]
@gustavomassa I'm not that familiar with cluster but if it's a single process then it will send all the data for the process as a while.  If it spawns a new node process for each worker then I think you will only get the data from the master process by default.  Is it [this package](https://www.npmjs.com/package/cluster) you're using?

**Comment by gustavomassa** [comment]
@sjanuary hello, I'm using the built-in cluster module of nodejs: [https://nodejs.org/api/cluster.html](url)
Internally they spawns new node process for each worker.

**Comment by Thinkscape** [comment]
This issue is ancient, but I can answer it for you.

Appmetrics nodejs plugin will be collecting process memory usage *per thread*, so if you use clustering or forking, it will separately report each thread's usage. Moreover, if the tags overlap, your reporting solution might actually show you the last-sent-value only.

For example, on a 2-core node, your node app will spawn 2 worker threads. If each thread/process uses 200MB each, appmetrics will keep sending `appmetrics.memory.process.physical` with a value of 200MB, while in reality, your node is consuming 400MB+ of RAM.

This isn't necessarily wrong, but it is a caveat to be considered when reporting on those values.
