### ISSUE TITLE
Global variables in probes can cause requests to be overwritten.

### ISSUE THREAD

**Issue by hhellyeribm** [RuntimeTools/appmetrics#61]
Several probes are storing request data and timer data in global variables which means that multiple events can end up overwriting each others data.

**Comment by seabaylea** [comment]
It looks like there's some mistaken use of global rather than local variables which means that if you have several events fired (particularly of the same type) in very quick succession than the data can be "merged".

This doesn't appear to affect HTTP too badly, but if there's multiple MySQL or MongoDB calls in the same HTTP request then some merging happens.

This is critical to fix as it relates to the correctness of the data.

**Comment by seabaylea** [comment]
I haven't found any issues with this in integration testing, so closing.
