### ISSUE TITLE
Appmetrics version incorrect when displayed in the Health Center GUI

### ISSUE THREAD

**Issue by tobespc** [RuntimeTools/appmetrics#78]
the Health Center gui currrently displays the appmetrics version  as the "Health Center agent version" which is basically the agent core version.  I would like to have the correct appmetrics version shown, e.g. 1.0.4

**Comment by tunniclm** [comment]
@tobespc I'd like to see a few further changes for this issue. The most important is that the common environment plugin (which is part of the healthcenter core agent) sends a blank value for jar.version (instead of not sending the property at all).

It appears as:
```
jar.version=
```

I also would like to see the core agent version being sent by the common environment plugin, rather than the Node environment plugin, if possible.

It would be really great if the appmetrics agent loader was not involved at all in sending the healthcenter core agent version (presently it sets a property for the comment environment agent to read that contains core agent version it gets from the AgentLoader API, since the common environment agent does not have access to the AgentLoader API itself.) The most straight-forward solution would be to have the core Agent set the property itself.

**Comment by tobespc** [comment]
I agree @tunniclm , I'll get the changes pushed through

**Comment by tobespc** [comment]
This issue will be  resolved in a future release of appmetrics as it requires modification of source code in another project as well as this one

**Comment by tobespc** [comment]
I'm closing this issue as the direction we are taking node monitoring it to use appmetrics-dash going forwards and not rely on healthcenter.
